name: Search tenders on rostender.info with GPT

on:
  schedule:
    - cron: '0 7,13 * * *'  #run 7 utc and 13 utc
  workflow_dispatch:  # Allows manual run

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Check if MYSELDON_PASS is set
      run: |
        if [ -z "${{ secrets.MYSELDON_PASS }}" ]; then
          echo "MYSELDON_PASS is not set!"
          exit 1
        else
          echo "MYSELDON_PASS is set!"
        fi
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run 7.py
      env:
        MYSELDON_PASS: ${{ secrets.MYSELDON_PASS }}
        MYSELDON_LOGIN: ${{ secrets.MYSELDON_LOGIN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python 6mysqldon.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add -A
        git diff --cached --exit-code || git commit -m "Automated update ($GITHUB_WORKFLOW)"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || echo "No changes to commit"
