# GSheet Action Documentation: https://github.com/marketplace/actions/gsheet-action
name: gsheet.action test

# Trigger the workflow only on 'workflow_dispatch' events
on: 
  workflow_dispatch:
    inputs:
      spreadsheetId:
        description: 'Spreadsheet ID'
        required: true
        default: ''
      linkToAttendies:
        description: 'linkToAttendies'
        required: true
        default: 'где берем список участников выставки'
      instructionOnSiteCrawl:
        description: 'Инструкция на что смотрим на сайте (напр это производитель)'
        required: false
        default: 'если это крупный производитель пиши Подходит. Если нет - Не подходит'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get list of attendies
        run: |
          echo ""
          
      - name: Read JSON file
        id: json_read
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const path = './test.json';
            const data = fs.readFileSync(path, 'utf8');
            return data;

      - id: 'update_worksheet'
        uses: jroehl/gsheet.action@v2.0.0
        with:
          spreadsheetId: ${{ github.event.inputs.spreadsheetId }}
          commands: |
            [
              { "command": "addWorksheet", "args": { "worksheetTitle": "<worksheetTitle>" }},
              { "command": "updateData", "args": { "data": ${{ steps.json_read.outputs.result }} }},
              { "command": "getData", "args": { "range": "'<worksheetTitle>'!A2:B3" } }
            ]
        env:
          GSHEET_CLIENT_EMAIL: "swap155-212716@appspot.gserviceaccount.com"
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: dump results
        env:
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
        run: echo "$RESULTS" | jq 
